tap 'homebrew/cask-fonts'

brew 'direnv'
brew 'libpq' # for psql
brew 'rbenv'

cask '1password'
cask 'adobe-creative-cloud'
cask 'backblaze'
cask 'battery-buddy'
cask 'cyberduck'
cask 'db-browser-for-sqlite'
cask 'discord'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'flux'
cask 'font-inconsolata-g'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'iterm2'
cask 'keybase'
cask 'microsoft-office'
cask 'omnidisksweeper'
cask 'paw'
cask 'slack'
cask 'splice'
cask 'spotify'
cask 'sublime-text'
cask 'tableplus'
cask 'visual-studio-code'
cask 'wireshark'
cask 'xctu'
cask 'zoom'

